language: python
python: 3.4
env: PROD
    
jobs:
 include:
  - stage: Script stage
    script: python test_planet.py 
    name: Unit Tests
  - stage: deploy
    name: Deploy Scripts
    script: python test_planet.py
