language: python
python: 3.4
env: PROD
    
stages:
- deploy
- scripting

jobs:
 include:
  - stage: scripting
    script: python test_planet.py 
    name: Unit Tests
  - stage: deploy
    name: Deploy Scripts
    script: python test_planet.py
