language: python
python: 3.4
env: PROD
    
stages:
- test
- scripting
- name: deploy
  if: branch = release

jobs:
 include:
  - script: python test_planet.py
    name: test script
  - stage: scripting
    if: branch = release
    script: python test_planet.py 
    name: Unit Tests
  - stage: deploy
    name: Deploy Scripts
    script: python test_planet.py
